export const UPDATE_PATIENT_LIST = "UPDATE_PATIENT_LIST";

export const UPDATE_PATIENT_FILE_LIST = "UPDATE_PATIENT_FILE_LIST";

export const UPDATE_FILE_UPLOAD_STATUS = "UPDATE_FILE_UPLOAD_STATUS";

export const DELETE_FILE_TWINS = "DELETE_TWINS";

export const FILE_STATUS = {
    INIT: "INIT",
    PENDING: "PENDING",
    COMPLETE: "COMPLETE"
}